site_name: Catalogue Open Data Santé

repo_url: https://github.com/petoulemonde/catalogue-open-data-sante
repo_name: Catalogue open data sante


nav:
  - Bienvenue! : README.md
  - Comment naviguer? : navigation_explanation.md
  - Roadmap: roadmap.md

  - Les fournisseurs de données: 
    - Santé Publique France: fournisseurs/spf.md
    - République française: fournisseurs/rep_francaise.md

  - Les boards de données:
    - Data.gouv.fr: boards/data_gouv_fr.md

  - Les bases de données:
    - Surveillance du Sars-Cov-2 dans les eaux usées - SUM'eau: 
      - Présentation: bases/sumeau/sumeau.md
      - sumeau-indicateurs-YYYY-mm-DD-HHhMM: bases/sumeau/sumeau_indicateurs.md
      - sumeau-stations-YYYY-mm-DD-HHhMM]: bases/sumeau/sumeau_stations.md


theme:
  name: material